services:
  db_first:
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=db1 
    - MYSQL_USER=user1
    - MYSQL_PASSWORD=pass1
    volumes:
    - ./db1_init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - mysql_firstDB:/var/lib/mysql
  db_secondDB:
    image: mysql:latest
    ports:
    - "3406:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=db2
    - MYSQL_USER=user2
    - MYSQL_PASSWORD=pass2
    volumes:
    - ./db2_init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - mysql_secondDB:/var/lib/mysql

volumes:
  mysql_firstDB:
  mysql_secondDB: